namespace: prod

backend:
  image: us-central1-docker.pkg.dev/nirmal-learning/demo-repo/backend
  tag: "v1"
  replicas: 3

frontend:
  image: us-central1-docker.pkg.dev/nirmal-learning/demo-repo/frontend
  tag: "v1"

mysql:
  image: mysql:8
  rootPassword: password
  database: demo
  storage: 10Gi

ingress:
  host: ivoxa.ai
  tlsSecret: prod-ivoxa-tls
